[package]
name = "oxide"
version = "0.1.0"
authors = ["purple"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
exe = "=0.4.6"
liboxide = { path = "liboxide/" }