[package]
name = "oxide"
version = "0.2.0"
authors = ["purple"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.7"
exe = "0.5.1"
liboxide = { path = "liboxide/" }
pkbuffer = "0.4.0"