[package]
name = "liboxide"
version = "0.1.0"
authors = ["purple"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exe = "=0.4.4"
compression = "0.1.5"